name: 'Actions Failed Log to Slack'
description: 'GitHub Actions to notify Slack of the contents of the log of failed jobs in GitHub Actions.'
author: 'swfz'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'alert-octagon'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'You must manually pass in secrets.GITHUB_TOKEN'
    required: true
  slack-webhook-url:
    description: 'Your Slack webhook url'
    required: true

# Define your outputs here.
# outputs:
#  time:
#    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
