name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'
  github-token:
    description: 'You must manually pass in secrets.GITHUB_TOKEN'
    required: true
  slack-webhook-url:
    description: 'Your Slack webhook url'
    required: true
  from-workflow-run:
    description: 'The workflow run that triggered this action'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
